reset_counter:
  name: Reset Carbon Counter
  description: Reset the carbon footprint counter for all or specific energy sensors
  fields:
    energy_entity_id:
      name: Energy Entity
      description: The energy entity to reset. Leave empty to reset all entities.
      required: false
      selector:
        entity:
          domain: sensor